name: puantaj_x
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+20

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  uuid: ^4.5.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  gap: ^3.0.0
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.0.0
  shared_preferences: ^2.3.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  excel: ^4.0.6
  package_info_plus: ^8.1.0
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

dependency_overrides:
  web: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/app_logo.png"
  android_12:
    image: "assets/icons/app_logo.png"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
